### ISSUE TITLE
missing translation for rosh hashana

### ISSUE THREAD

**Issue by ilayDev** [hebcal/hebcal-es6#10]
the render function on Rosh Hashana event always returns the English string even when the locale parameter is set to 'he' or 'fr'
it's works fine for Rosh Hashana day 2 but not for day 1

for example:
events /*
[
  HolidayEvent {
    date: HDate { month: 7, day: 1, year: 5781 },
    desc: 'Rosh Hashana 5781',
    mask: 33,
    attrs: [Object: null prototype] {}
  },
  HolidayEvent {
    date: HDate { month: 7, day: 2, year: 5781 },
    desc: 'Rosh Hashana II',
    mask: 5,
    attrs: [Object: null prototype] {}
  }
] */

var translateToHebrew = events.map(ev=>ev.render('he') );  //[ 'Rosh Hashana 5781', 'רֹאשׁ הַשָּׁנָה יוֹם ב׳' ]

**Comment by mjradwin** [comment]
Confirmed. We'll work on a fix.

**Comment by mjradwin** [comment]
Fixed in `@hebcal/core@2.5.2`
