### ISSUE TITLE
Is Hebcal's interpretation of the Eisenberg triennial cycle in error?

### ISSUE THREAD

**Issue by bellzw** [hebcal/hebcal-es6#133]
The Eisenberg triennial cycle for Va'yekhel-Pekudei seems to say that when these sections are read together in years 1 and 2 of a cycle and are apart in year 3, as is the case for 5780, 5781, and 5782, the reading from Va'yekhal is Ex: 35:1-36:19.  Hebcal reports Ex: 36:20 - 28:20. 

I've attached an annotated image of the relevant page from the Eisenberg document for Va'yekhel-Pekudei and marked the years corresponding to years 1 - 3, and indicated what Hebcal reports.

![Capture](https://user-images.githubusercontent.com/51066449/155038919-1fa80e11-f5bf-489c-ae62-0d8712492217.PNG)

There also seems to be a discrepancy for Tazriah-Metzorah.  The 5780-5782 cycle also seems to be a together, together, separate group but Hebcal does not report Lev 12:1 - 13:28.

It appears that Hebcal is using the next cycle, but that doesn't work for Acharei Mot, later this year.

Perhaps Hebcal doesn't use the Eisenberg calendar system to which Hebcal links?  Have I misinterpreted Eisenberg's tables?

**Comment by mjradwin** [comment]
In December 2021, Hebcal triennial Torah readings were updated to reflect the November 2020 responsa from the Committee on Jewish Law and Standards of the Rabbinical Assembly.

https://www.rabbinicalassembly.org/sites/default/files/2021-09/cohen-triennial.pdf

The CJLS modified the triennial cycle for some combined parshiyot to change the reading for year 3 to be the third section of the parashah.

The following parshiyot have been modified:

Vayakhel
Tazria
Achrei Mot
Behar
Chukat
Matot

Further details are available in the responsa: Modification of the Triennial Cycle Readings for Combined Parashot in Certain Years, Rabbi Miles B. Cohen, November 16, 2020

https://github.com/hebcal/hebcal-leyning/commit/515fd2c7939f485374692be6b66144dd9750584b

**Comment by bellzw** [comment]
Thanks for the quick response.  I was unaware of the Cohen modification.

 

This closes the issue for me.  I might suggest that you add a link to the cohen-triennial and a note that it amends the Eisenberg document.
