### ISSUE TITLE
Shabbat Chol Hamoed Sukkot bug in REST API and HTML

### ISSUE THREAD

**Issue by pbleic** [hebcal/hebcal-es6#160]
You have a problem with using your own data on your website.  For 2022-10-15 the "leyningmaftir" from your REST API is Numbers 29:26-29:31.  This is the standard maftir for Chol Hamoed Sukkot, and is the same as Chabad's: https://www.chabad.org/parshah/default_cdo/aid/137613/jewish/Sukkot.htm

However, your website https://www.hebcal.com/holidays/sukkot-2022?i=on  lists Numbers 29:29-34.  Have no idea where this comes from other than it being the 4th aliyot of Hoshana Raba, the next day.   

And, interestingly, your puzzling concatenation field, "leyningtorah" on that day shows: Exodus 33:12-34:26; Numbers 29:17-22, 29:20-25, 29:23-28, 29:26-31, 29:29-34  Which is not at all what is read.  But the final 8 characters: "29:29-34" are the same as the odd "leyningmaftir."

**Comment by mjradwin** [comment]
Thanks for finding this bug. We have corrected the issue and pushed changes to the website.
