### ISSUE TITLE
Custom export - missing data

### ISSUE THREAD

**Issue by essel-dev** [hebcal/hebcal-es6#181]
Thanks for making Hebcal available!

I found some data missing when trying the following imports into Google Calendar, see attached screenshot:
1. Zmanim for [Candle lighting and Havdalah only](https://www.hebcal.com/hebcal?v=1&i=off&year=2022&yt=G&lg=a&c=on&geo=geoname&zip=&city=&geonameid=2803138&city-typeahead=Antwerpen%2C+Flanders%2C+Belgium&b=18&M=on&m=) highlighted in blue.
2. Zmanim for [all events](https://www.hebcal.com/hebcal?v=1&maj=on&min=on&nx=on&mf=on&ss=on&mod=on&s=on&i=off&year=2022&yt=G&lg=a&c=on&geo=geoname&zip=&city=&geonameid=2803138&city-typeahead=Antwerpen%2C+Flanders%2C+Belgium&b=18&M=on&m=) highlighted in grey.

With export 1 the Havdalah times are missing for:
1. motzei Rosh Hashana
2. motzei Yom Kippur

This happens yearly.

![Screenshot 2022-06-17 18 51 25](https://user-images.githubusercontent.com/84270422/174349682-d9bbb49a-222b-47f9-8dca-fe4de79ed450.png)

**Comment by mjradwin** [comment]
Thanks for the bug report! We have fixed the issue for the missing Havdalah times on motzei Rosh Hashana and Yom Kippur.

Google Calendar may take up to 7 days to refresh iCalendar feeds
