### ISSUE TITLE
HDate: Time ignored? Why?

### ISSUE THREAD

**Issue by MDjavaheri** [hebcal/hebcal-es6#19]
I find this module to be extremely helpful for a project I'm working on, but why are hours ignored when creating a new HDate? Isn't it pretty important to know if an event if before or after sunset?
I originally posted this issue in [hebcal-js](https://github.com/hebcal/hebcal-js/issues/85), but then someone pointed me to this newer version of the module, so I'm posting it here, too. 
As an aside, how come there's no mention of this es6 version on the original js port's readme?

**Comment by MDjavaheri** [comment]
Peeking through the code, it seems that it's the `greg.greg2abs()` that's responsible for this.

**Comment by MDjavaheri** [comment]
Is this the only workaround?
```
onChange(e){
        const civil = new Date(e);
        let hebrew = new HDate(civil);
        const zemanim = new Zmanim(civil, userLat, userLong);
        const shekiah = zemanim.shkiah();
        if (civil > shekiah) {
            hebrew = hebrew.next();
        }
}
```

**Comment by MDjavaheri** [comment]
Except that is strangely telling me that `zemanim.shkiah() === 'Wed Mar 03 2021 07:57:21 GMT-0500 (Eastern Standard Time)'` which makes no sense in NYC.

**Comment by mjradwin** [comment]
The HDate class does not represent a time, only a date. The constructor deliberately ignores the hour/minute/second portion of a native Date object. The HDate object has no notion of location or timezone. Please use the Zmanim class for those purposes.

What latitude and longitude are you using for NYC? Shkiah is calculated correctly for us and we use 40.71427, -74.00597.

Please send a more complete test script if you would like assistance debugging.

**Comment by MDjavaheri** [comment]
Thanks for the quick help.
I was missing the negative in longitude!

**Comment by MDjavaheri** [comment]
Just curious about how come there's no mention of this es6 version on the original js port's readme

**Comment by sbc640964** [comment]
Is it possible to use the time zone of the system / browser?
Does a specific use case in each time zone date change at sunset?

**Comment by mjradwin** [comment]
No, it's possible to calculate sunset precisely using only the time zone of the system/browser. You need the user latitude and longitude to be able to determine sunset. 

You can use the browser [Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition) to get lat/long like this:

```js
const now = new Date();
let hdate = new HDate(now);
if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function (position) {
        const userLat = position.coords.latitude;
        const userLong = position.coords.longitude;
        const zman = new Zmanim(now, userLat, userLong);
        const sunset = zman.shkiah();
        if (now > sunset) {
            hdate = hdate.next();
        }
    });
}
```
