### ISSUE TITLE
Language mismatch between hDate.getMonthName and its documentation.

### ISSUE THREAD

**Issue by majortom64** [hebcal/hebcal-es6#2]
According to the ReadMe:

hDate.getMonthName() ⇒ string

Returns untranslated Hebrew month name.

Since it returns the English transliteration for the Hebrew month, either the docs should be:

Returns the English transliteration of the Hebrew month (without regard to locale).

Or the function should be changed to return the Hebrew month in Hebrew.

**Comment by mjradwin** [comment]
Updated documentation to clarify that `HDate.getMonthName()` always returns an English transliteration.
