### ISSUE TITLE
get full month object

### ISSUE THREAD

**Issue by sbc640964** [hebcal/hebcal-es6#20]
How to get an object of the whole month or year
Like hebcal() in the hebcal-js package?

**Comment by mjradwin** [comment]
You probably want to use the [HebrewCalendar.calendar()](https://github.com/hebcal/hebcal-es6/blob/main/README.md#HebrewCalendar.calendar) function.

For example,
```js
import {HebrewCalendar} from '@hebcal/core';
const options = {
  year: 1981,
  isHebrewYear: false,
  sedrot: true,
};
const events = HebrewCalendar.calendar(options);
```
