### ISSUE TITLE
Shouldn't only candle lighting and havdalah times show up?

### ISSUE THREAD

**Issue by essel-dev** [hebcal/hebcal-es6#201]
>Fasting times for Tish'a B'Av shouldn't show up in export with [Candle lighting and Havdalah only](https://www.hebcal.com/hebcal?v=1&i=off&year=2022&yt=G&lg=a&c=on&geo=geoname&zip=&city=&geonameid=2803138&city-typeahead=Antwerpen%2C+Flanders%2C+Belgium&b=18&M=on&m=)

![image](https://user-images.githubusercontent.com/84270422/174624960-28da2ab1-8614-44fb-8621-ff38e514a80b.png)

_Originally posted by @essel-dev in https://github.com/hebcal/hebcal-es6/issues/181#issuecomment-1160526624_

**Comment by mjradwin** [comment]
We've revised the header on the form to indicate **Candle-lighting & Fast times**

<img width="705" alt="Jewish_Calendar_5783_Palo_Alto__CA_94303_-_Hebcal" src="https://user-images.githubusercontent.com/3769045/208310641-a3febf40-cfb1-4216-b33f-0689a4a65cfd.png">
