### ISSUE TITLE
`TimedEvent` type annotations do not expose timing information

### ISSUE THREAD

**Issue by elanhamburger** [hebcal/hebcal-es6#207]
When generating a calendar with candle lighting times in Typescript, the `TimedEvent`s representing candle lighting do not include any way to actually access the timing information.

```typescript
import { HebrewCalendar, Location, TimedEvent } from "@hebcal/core";

HebrewCalendar.calendar({
    year: 2022,
    month: 8,
    candlelighting: true,
    location: Location.lookup("Baltimore"),
    noHolidays: true
}).forEach(event => {
    console.log(event.eventTime); // <-- Refuses to compile
    console.log((event as TimedEvent).eventTime); // <-- Refuses to compile
});
```

The [`.d.ts` entry for `TimedEvent`](https://github.com/hebcal/hebcal-es6/blob/f0a45e0681d1752f06de9fd83d49fc2c331cdd1f/hebcal.d.ts#L983) does not include entires for `eventTime` or `eventTimeStr`, and the class itself does not expose any getter methods for the same.

```
Property 'eventTime' does not exist on type 'TimedEvent'.
```

Trying to retrieve the information from the Gregorian `Date` also fails, because timing information is lost in the conversion to `HDate`.

```typescript
HebrewCalendar.calendar({
    // ...
}).forEach(event => {
    console.log(event.getDate().greg()); // <-- Prints 2022-08-05T00:00:00Z (for example)
});
```

I'm happy to write a PR if you'd like, but I didn't know if you manually edit the `.d.ts` or if it's generated, or if you wanted to expose the properties or write getters for them.

**Comment by mjradwin** [comment]
Thanks for the bug report! Fixed in 3.42.1
