### ISSUE TITLE
Shabbat Times Gives Date But Not Times

### ISSUE THREAD

**Issue by DaniSpringer** [hebcal/hebcal-es6#219]
Example call to RSS API:
https://www.hebcal.com/shabbat?cfg=r&leyning=off&geonameid=3173435

Output: Friday, September 09, 2022
Torah: Deuteronomy 21:10-25:19
Haftarah: Isaiah 54:1-10
Saturday, September 10, 2022

NOTE: I am using a Siri shortcut to parse the output, and will be happy to provide more info, if someone is here to read that.

EDIT: in fact, many parameters make no difference at all whether they included in the URL, excluded, and no matter what value is passed to them (on/off etc).

**Comment by mjradwin** [comment]
Hi, thanks for your message. We're having trouble reproducing the problem you describe. When we fetch the URL you pasted above, we see the following excerpt among the RSS feed items:

```xml
<item>
<title>Candle lighting: 19:28</title>
<link>https://www.hebcal.com/shabbat?geonameid=3173435&amp;M=on&amp;lg=s&amp;dt=2022-09-09&amp;utm_source=shabbat1c&amp;utm_medium=rss#20220909-candle-lighting</link>
<guid isPermaLink="false">https://www.hebcal.com/shabbat?geonameid=3173435&amp;M=on&amp;lg=s&amp;dt=2022-09-09#20220909-candle-lighting</guid>
<description>Friday, September 09, 2022</description>
<category>candles</category>
<pubDate>Fri, 09 Sep 2022 17:28:00 GMT</pubDate>
<geo:lat>45.46427</geo:lat>
<geo:long>9.18951</geo:long>
</item>
```

Note specifically the `title` field says `Candle lighting: 19:28` 

Note also the `pubDate` field represents the same date in RFC-822 date-time format (`Fri, 09 Sep 2022 17:28:00 GMT`)

If you don't see the above `<item>`, could you please paste the full output of the following command?

```
curl --compressed -v 'https://www.hebcal.com/shabbat?cfg=r&leyning=off&geonameid=3173435'
```

**Comment by mjradwin** [comment]
Hi @DaniSpringer, were you able to confirm that the RSS API is returning times?

**Comment by mjradwin** [comment]
We haven't heard back from you, so we are inferring that silence means that the RSS API is working as expected. Feel free to reopen this issue if something changes on your end. 

Shana tova!
