### ISSUE TITLE
Sunrise/sunset changes by large amount between February and March

### ISSUE THREAD

**Issue by sdubois** [hebcal/hebcal-es6#22]
Created an issue on the wrong project, so reposting here. 

Original ticket: https://github.com/hebcal/hebcal/issues/213

**Comment by mjradwin** [comment]
Thanks. We will do some investigation. We are using the solar-calc JavaScript library, and you have provided helpful guidance.

**Comment by sdubois** [comment]
Started taking a closer look into the solar-calc library and I think this issue is arising from a bug in how it calculates the Julian date. Here are some examples from Dec 31 2020 to Mar 2 2021.

`Dec 31 2459214.5
Jan 01 2459213.5
Feb 27 2459269.5
Feb 28 2459270.5
Mar 1  2459274.5
Mar 2  2459275.5`

When you compare these dates to the dates provided by an online conversion tool such as https://www.onlineconversion.com/julian_date.htm you can see that everything from Jan 1 to Feb 28 is incorrect.

**Comment by mjradwin** [comment]
Agreed - the problem was indeed exactly as you describe. I've implemented a fix and have published new npm package `@hebcal/core@3.9.1`. I will deploy to the website tomorrow.

**Comment by mjradwin** [comment]
Changes deployed.

https://www.hebcal.com/zmanim?cfg=json&start=2021-02-27&end=2021-03-02&geo=zip&zip=07666

Closing this bug. Some URLs may be cached for up to 30 days so if you find something that looks wrong, check the `Age` HTTP header.
