### ISSUE TITLE
Is it possible to use hDate.renderGematriya() without nikud?

### ISSUE THREAD

**Issue by EliezerB123** [hebcal/hebcal-es6#290]
Is it possible to use hDate.renderGematriya() without nikud?

I see 
`new hDate().renderGematriya()`
and  
`new hDate().render('he-x-NoNikud').toString()`

But I don't see any way to combine the two, so we get the Gematriya without Nikud.

**Comment by mjradwin** [comment]
Good suggestion. We could add an optional boolean parameter to suppress nikud (default false) to help address this.

In the meantime you can use `Locale.hebrewStripNikkud()` to remove nekudot from the string

https://github.com/hebcal/hebcal-es6/blob/main/README.md#Locale.hebrewStripNikkud

**Comment by mjradwin** [comment]
Fixed in v3.50.4
