### ISSUE TITLE
Is there a simple way to turn a Date object into the equivalent HDate?

### ISSUE THREAD

**Issue by majortom64** [hebcal/hebcal-es6#3]
Unless I am missing it, I cannot find a single step way to turn a JS Date into the HDate for the same day. Related question (maybe just needs documentation): What is the difference between: getBirthdayOrAnniversary(hyear, gdate) ⇒ HDate
and
getYahrzeit(hyear, gdate) ⇒ HDate ?

**Comment by mjradwin** [comment]
HDate has an overloaded constructor that takes a Date as a single argument.
Hours and minutes and seconds are ignored. The documentation needs to be
updated.

Birthday and Yahrzeit calculations are similar but differ in special cases
in Adar, Cheshvan and Kislev.

https://www.hebcal.com/home/54/anniversaries-adar-cheshvan-kislev

-- 
-- Sent from my mobile device
