### ISSUE TITLE
21 Nisan 5781 is missing ParshaEvent

### ISSUE THREAD

**Issue by yochanan-sheinberger** [hebcal/hebcal-es6#30]
maybe it's not relevant any more. but if it's caused by an algorithm problem it could occur again.

thank you!

**Comment by mjradwin** [comment]
21 Nisan is the 7th day of Pesach. The HebrewCalendar.calendar() function generates ParshaEvent on Saturdays only for regular parasha haShavua, not for holiday Torah readings. When a yom tov holiday like Pesach occurs on Shabbat, you wouldn't expect to see a ParshaEvent.
