### ISSUE TITLE
Hebrew string Date conversion to either Normal Hebrew date or Gregorian Date

### ISSUE THREAD

**Issue by shivrajgodle** [hebcal/hebcal-es6#335]
const hd = new HDate(date.day, month, date.year);
return hd.renderGematriya(true);

by this two lines of code we can able to make the conversion of Hebrew date to Hebrew text date (כ״ד בְּתַמּוּז תשפ״ג). but we can't do Hebrew text date to hebrew date(24th of Tamuz, 5783) or Gregorian Date(Wed, 12 July 2023) using the library. i have checked whole documentation but not found anything solid which gives me the option to do the above mentioned task.

**Comment by mjradwin** [comment]
If you are trying to convert from Gregorian string, you can generally use something like this:

```javascript
const dt = new Date ('june 11 2013');
const hd = new HDate(dt);
```

Would that work for you?

**Comment by shivrajgodle** [comment]
No , my scenario is like that i am converting Gregorian date (Wed, 12 July 2023) to Hebrew Text date (כ״ד בְּתַמּוּז תשפ״ג) using below code. 

const hd = new HDate(date.day, month, date.year); 
return hd.renderGematriya(true); 

but after conversion using hd.renderGematriya(true); we are getting  כ״ד בְּתַמּוּז תשפ״ג date. but if any user changes this date to another date like כ״ז בְּתַמּוּז תשפ״ג then we have no options to convert this kind of hebrew text date to Gregorian date that is  15 July 2023 or Hebrew date 27th of Tamuz, 5783. so we need a Hebrew text date conversion mechanism by which we can easily convert any Hebrew text date to Gregorian date or Hebrew Date. as a Non Jewish people we can not read Hebrew text date , so if you have this system to convert this text date to Gregorian date then it will be easy for us.

**Comment by mjradwin** [comment]
Understood. This is something you will probably need to implement outside of the @hebcal/core library. There is no standard format for Hebrew Date strings so implementing it in a general way would be very complicated and difficult to guarantee correctness. We would like to support that eventually.

To do this correctly you would want to take a string and split into 3 parts on whitespace.

Then, for the first and 3rd components (day and year), you will want to convert from Gematriya string to numbers. There is no function built-in to @hebcal/core that does that currently, but you could use this library to do so:

https://github.com/Scimonster/js-gematriya

Then, for the middle component (month), apply the function `Locale. hebrewStripNikkud()` to remove any vowels, then trim a leading bet (ב) from the name of the month if present.

Then, create a new Hebrew Date object using

```javascript
const hd = new HDate(day, month, year);
```

**Comment by mjradwin** [comment]
We have added a new static constructor to HDate to address this. Please give it a shot and let us know if it works for you

### HDate.fromGematriyaString(str, currentThousands) ⇒ [<code>HDate</code>](#HDate)
Construct a new instance of `HDate` from a Gematriya-formatted string

**Kind**: static method of [<code>HDate</code>](#HDate)  

| Param | Type | Default |
| --- | --- | --- |
| str | <code>string</code> |  | 
| currentThousands | <code>number</code> | <code>5000</code> | 

**Example**  
```js
HDate.fromGematriyaString('כ״ז בְּתַמּוּז תשפ״ג') // 27 Tamuz 5783
 HDate.fromGematriyaString('כ׳ סיון תש״ד') // 20 Sivan 5704
 HDate.fromGematriyaString('ה׳ אִיָיר תש״ח') // 5 Iyyar 5708
```

**Comment by shivrajgodle** [comment]
Thanks Michael J. Radwin for this kind of support. will try this in my application and let you know its result.

**Comment by shivrajgodle** [comment]
Update:- @mjradwin  I have used HDate.fromGematriyaString('כ״ז בְּתַמּוּז תשפ״ג')  and it works great in my project. i appreciate your quick response in this issue. **Thank You once again.**
