### ISSUE TITLE
Uncaught TypeError when using package with Vite

### ISSUE THREAD

**Issue by Doreen-Schwartz** [hebcal/hebcal-es6#358]
Hello, I've been using your package for a React project that was based on the Create React App framework and have had no issue utilizing it. Since the framework is deprecated and has security issues, I need to migrate our project to Vite. 

Unfortunately, I encountered the following error when attempting to run it:
![image](https://github.com/hebcal/hebcal-es6/assets/126075185/9be93e18-09b5-467e-a6ea-3c69d7929988)

Following the [link mentioned in the warning above](https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility), I see that the issue is caused by a Node module, `events`, being used. Since Vite does not automatically apply polyfills, this error appears. 

Though I could install the polyfill to fix this issue, I noticed that the Readme mentions this package is meant to be compatible with browsers, so I wanted to open this issue.

**Comment by mjradwin** [comment]
Thanks for writing. Please migrate your application to use [@hebcal/core](https://www.npmjs.com/package/@hebcal/core) which is actively maintained. The API in `@hebcal/core` is very similar, but not identical, to the no-longer-maintained [hebcal](https://www.npmjs.com/package/hebcal) package.

Based on the error message you posted above, it appears that you are still using the deprecated `hebcal` API, which hasn't been updated in 4+ years.

**Comment by Doreen-Schwartz** [comment]
I see what you mean. You are correct, the API was indeed the old one. I've switched it and the problem was resolved, thank you.
