### ISSUE TITLE
Set options.hour12 to true still returns the 24h format

### ISSUE THREAD

**Issue by meyer59** [hebcal/hebcal-es6#378]
Hi
The options.hour12 set to true seems to always return the 24h format in the generated strings (like Molad infos in the Mevarhim Shabbat object). Even if i force the local the string is in 24h format. 
Is there something specific to do to have the 12h format in the result strings ? 
Thank you

**Comment by mjradwin** [comment]
Thanks for the bug report. We will investigate and get back to you

**Comment by mjradwin** [comment]
Partially fixed (for Candle lighting and Havdalah) in v5.0.7.

Not yet fixed for the Molad memo in the Mevarhim Shabbat object

**Comment by meyer59** [comment]
Thanks a lot. I appreciate you work here

**Comment by meyer59** [comment]
Hello @mjradwin 
Did you have some time to check for the  Molad memo ?

**Comment by mjradwin** [comment]
Fixed in 5.1.0
