### ISSUE TITLE
What the best way to get  MGA  Shema / Shacharit as 16.1 degrees

### ISSUE THREAD

**Issue by meyer59** [hebcal/hebcal-es6#380]
Hi
For MGA Shema and Shacharit there 3 opinion, here is a screenshot from MyZmanim showing them:  
![Captu re](https://github.com/hebcal/hebcal-es6/assets/9505463/72ff37c2-8bbb-4a08-8a18-638de6cfa8ce)

Using the `zmanim.sofZmanShmaMGA()` and `zmanim.sofZmanTfillaMGA()` seems to return the time according to _fixed 72 minutes_, what the best way to get the time _using 72 minutes as 16.1 degrees_ ?

**Comment by mjradwin** [comment]
See these new functions in version 5.0.7

* [Zmanim.sofZmanShmaMGA16Point1()](https://github.com/hebcal/hebcal-es6/blob/main/README.md#Zmanim+sofZmanShmaMGA16Point1) ⇒ <code>Date</code>
* [Zmanim.sofZmanTfillaMGA16Point1()](https://github.com/hebcal/hebcal-es6/blob/main/README.md#Zmanim+sofZmanTfillaMGA16Point1) ⇒ <code>Date</code>
