### ISSUE TITLE
Is there a way to get parsha and even info?

### ISSUE THREAD

**Issue by isaacfink** [hebcal/hebcal-es6#414]
For example I want a way to get the following string (in hebrew) 
```
parshas vayijra shabbos chol hamoed
```
I had this exact functionality at some point with a single function without constructing the string myself, but I don't remember how I did it

**Comment by mjradwin** [comment]
For a given Saturday, you can get all of the events on the date and then render them as Hebrew using something like the following:

```js
import {HebrewCalendar, HDate} from '@hebcal/core';

const saturday = new Date(2024, 3, 6); // 2024-04-06
const hd = new HDate(saturday);
const events = HebrewCalendar.calendar({
  start: hd,
  end: hd,
  sedrot: true,
});

const strs = events.map((ev) => ev.render('he'));
const str = strs.join(' ');
console.log(str); // 'שַׁבָּת הַחֹדֶשׁ פָּרָשַׁת שְּׁמִינִי'
```
