### ISSUE TITLE
No seaLevelSunrise() method on Zmanin

### ISSUE THREAD

**Issue by YizYah** [hebcal/hebcal-es6#417]
The documentation refers to the method [seaLevelSunrise()](https://github.com/hebcal/hebcal-es6?tab=readme-ov-file#Zmanim+seaLevelSunrise) for the Zmanim object. But it does not appear to exist on the object.

This method would be quite useful in Israel, because it seems to me that the widely accepted calendar "Itim Levina" uses elevation for shkeya, but not for neitz.

Of course, there is a workaround to create two Zmanim instances and to make whatever calculations are necessary, but it would be nice to have just one.

Really, if I am correct about the way these times are being calculated in Israel, the ideal would be to be able to create an instance of a Zmanim with elevation used only for sunset but not for sunrise.

**Comment by mjradwin** [comment]
Fixed in 5.3.1

**Comment by YizYah** [comment]
Amazing turnaround @mjradwin thanks!
