### ISSUE TITLE
holidayDesc type not exporting

### ISSUE THREAD

**Issue by YizYah** [hebcal/hebcal-es6#440]
The `hebcal.d.ts` file does not include `holidayDesc`.

How is that file being generated?

I do not see any indication in `package.json`  that the `hebcal.d.ts` file is being generated automatically.

Is the `hebcal.d.ts` file being manually maintained? I imagine you are somehow generating it. If not, I'd be concerned about duplicity of code--a change to one version of `holidayDesc` may not be updated in the other. 

Could `hebcal.d.ts` be automatically generated by setting `"declaration": true` in a `tsconfig.json` file and then running `tsc`?

At any rate, if it's all manual, then `holidayDesc` does need to be added there.

**Comment by mjradwin** [comment]
It's being manually maintained. If we ever get around to rewriting the code in TypeScript we'll get it generated.

I'll get it added and fixed.
