### ISSUE TITLE
Eruv Tavshilin implemenation

### ISSUE THREAD

**Issue by PupaRebbe** [hebcal/hebcal-es6#445]
Not sure which class should implement this, probably HebrewCalendar.
Here is the code:
```js
function eruvTavshilin(dt, il){
    if(dt.getDay() <3 || dt.getDay() >4) return false;
    const today = new HDate(dt);
    const friday = today.after(5), tomorrow = today.next();
    if(!isChag(friday, il) || isChag(today, il) || !isChag(tomorrow, il)) return false;
    return true;
}

function isChag(dt, il){
    const options = {
        start: dt,
        end: dt,
        mask: flags.CHAG,
        il: il
    };
    const events = HebrewCalendar.calendar(options);
    return Boolean(events.length);
}
```

**Comment by mjradwin** [comment]
Added to 5.4.0

### HebrewCalendar.eruvTavshilin(date, il) ⇒ <code>boolean</code>
Eruv Tavshilin

**Kind**: static method of [<code>HebrewCalendar</code>](#HebrewCalendar)  

| Param | Type |
| --- | --- |
| date | <code>Date</code> \| [<code>HDate</code>](#HDate) | 
| il | <code>boolean</code> |
