### ISSUE TITLE
Is there a way to get mincha ketana 72 minutes?

### ISSUE THREAD

**Issue by isaacfink** [hebcal/hebcal-es6#447]
I am not sure how to calculate it but there is a mincha ketana that relies on 72 minutes, is there a way to get that in hebcal?

**Comment by YizYah** [comment]
Hi @isaacfink , what do you mean "relies on 72 minutes"? Do you mean Rabenu Tam LeCoola (that is, they consider shkeya to be 72 minutes after sunset).

**Comment by mjradwin** [comment]
There's a version of mincha ketana according to the Magen Avraham with the day starting 72 minutes before sunrise and ending 72 minutes after sunset. 

https://github.com/KosherJava/zmanim/blob/master/src/main/java/com/kosherjava/zmanim/ComplexZmanimCalendar.java#L1973

We don't have this available in Hebcal but we could add this.

**Comment by PupaRebbe** [comment]
Something like this:
```js
minchaKetanaMGA() {
  const [alot72, temporalHour] = this.getTemporalHour72();
  return new Date(alot72.getTime() + (9.5 * temporalHour));
}
```

**Comment by isaacfink** [comment]
Thanks @PupaRebbe that's what I ended up oding but I had to calculate temporal hour myself, where is this function?

**Comment by isaacfink** [comment]
@mjradwin That's exactly the one, I am not an expert in zmanim but I am comparing it to an existing luach, the one you linked is the one I needed and the implementation from @PupaRebbe is the correct one (at least for the couple of days I tested it for) there are some off by one issues with with rounding but it's the same implementation

**Comment by PupaRebbe** [comment]
> Thanks @PupaRebbe that's what I ended up doing but I had to calculate temporal hour myself, where is this function?

https://github.com/hebcal/hebcal-es6/blob/b9ed641ace56dcaa246183c21de7126b5794e85a/src/zmanim.ts#L265

**Comment by mjradwin** [comment]
We'll get a release out within an hour. Just finishing up unit tests

**Comment by mjradwin** [comment]
Added to `@hebcal/core` 5.4.4
