### ISSUE TITLE
Not showing hebrew language in calanader

### ISSUE THREAD

**Issue by Tygro101** [hebcal/hebcal-es6#449]
When using local of 'he' in calendar option I'm always getting results in English 
i was wandering what do i miss
code snippet : https://stackblitz.com/edit/vitejs-vite-mpsr6d?file=src%2FApp.tsx
image 
<img width="809" alt="image" src="https://github.com/hebcal/hebcal-es6/assets/9966735/674d91ea-d0c2-4cf8-adde-038fff2f6e7b">

Thank you 🥇

**Comment by Tygro101** [comment]
Ok, i have notice that i should use '.render('he')', i was sure there is native Hebrew support

**Comment by mjradwin** [comment]
We have updated the documentation to explain more clearly that the `desc` field contains the untranslated title of this event. Note that these description strings are always in English and will remain stable across releases. To get the title of the event in another language, use the `render()` method.

https://hebcal.github.io/api/core/classes/Event.html

**Comment by Tygro101** [comment]
@mjradwin Thank you very much, your effort is very appreciated!
