### ISSUE TITLE
All events are one day to early

### ISSUE THREAD

**Issue by nordentwickler** [hebcal/hebcal-es6#458]
Hello there, 

maybe this isn't an issue, its more like an understanding thing. We are using hebcal/core and fullcalendar on a vue based website: [https://jg-ffm.de/kultur-events/veranstaltungskalender](https://jg-ffm.de/kultur-events/veranstaltungskalender)

This is our call to get all events from hebcal:
```
const location = new Location(50.1138147,8.6609245, false, 'Europe/Berlin', 'Frankfurt am Main', 'DE', null, 112)

const holidays = HebrewCalendar.calendar({
                start,
                end,
                candlelighting: true,
                location,
                candleLightingMins: 30,
                useElevation: true,
                sedrot: true,
                havdalahDeg: 8.57,
                locale: document.documentElement.lang,
            }).map(event => {
                const localizedTitle = event.render().split(': ')[0];

                if (event instanceof CandleLightingEvent
                    || event instanceof HavdalahEvent
                    || event instanceof TimedEvent
                ) {
                    return {
                        title: localizedTitle,
                        start: convertToUTC(event),
                        extendedProps: {
                            isReligious: true,
                            isCandleLighting: true,
                            styles: {
                                '--background-color': '195 185 161',
                                '--foreground-color': '77 73 73',
                            }
                        },
                        textColor: '#9B947D'
                    }
                }
```

`start` and `end` are based of the calendar range which is selected by the user. When i look up **Simchat Torah** on hebcal.com there is this date:

> begins at sundown on Thursday, 24 October 2024 and ends at nightfall on Friday, 25 October 2024.

For my customer, the jewish community of Frankfurt am Main, it is clear that Simchat Torah is on Friday 25.10. Our Implementation with the code above says it is 24.10.

Does anybody know, where we do have a misunderstanding in the use of hebcal/core? We would be very thankful about any kind of help or advice, where we should start to look at.

**Comment by mjradwin** [comment]
Based on your code sample, the error very likely exists in your app's `convertToUTC` function.

hebcal/core returns `Date` objects in th **local** timezone, not in UTC. You should use something like

```js
const hdate = event.getDate();
const date = hdate.greg();
const year = date.getFullYear();
const monthNum = date.getMonth() + 1;
const day = date.getDate();
```

**Comment by nordentwickler** [comment]
Actually we are doing the conversion with `.greg()` already:

```
    const convertToUTC = (event) => {
                if (!event.eventTime) {
                    return event.date.greg()
                }

              return new Date(event.eventTime.getTime() - event.eventTime.getTimezoneOffset() * 60_000);
            }
```

**Comment by nordentwickler** [comment]
We found the problem in the fullcalendar implementation, it was set to UTC and not to local. Thanks for your help!
