### ISSUE TITLE
dailyLearning not showing?

### ISSUE THREAD

**Issue by mosheYakov** [hebcal/hebcal-es6#466]
Hi,

I have added the dailyLearning option in my calOptions like so: 

`dailyLearning: {'dafYomi': true},`

but still, no daily learning events are coming up. Am I missing something?

**Comment by mjradwin** [comment]
You must also import `@hebcal/learning` for this feature to work.

```js
import {HebrewCalendar} from '@hebcal/core';
import '@hebcal/learning';

const events = HebrewCalendar.calendar({
  noHolidays: true,
  dailyLearning: {dafYomi: true},
});
```

**Comment by mosheYakov** [comment]
I did import `@hebcal/learning` but it returns an empty array.

I'm running it on a node server, not in a browser, makes a difference?

**Comment by mjradwin** [comment]
If you include both packages it should work just fine on either browser or node.js. 

Can you post a link to your full project repository? We have tested this and it should work using the example we posted above, but if you have a repo that demonstrates it not working we could investigate further.
