### ISSUE TITLE
iCloud

### ISSUE THREAD

**Issue by Perezari** [hebcal/hebcal-es6#56]
why can i add this calendar automatically to icloud?

**Comment by mjradwin** [comment]
If you'd like a Jewish holiday calendar on iCloud, here are some step-by-step instructions

[iPhone & iPad](https://www.hebcal.com/home/77/iphone-ipad-jewish-holidays)

[macOS desktop](https://www.hebcal.com/home/79/apple-ical-import-hebcal-jewish-calendar)
